######################################################################
<<<<<<< HEAD
# Automatically generated by qmake (2.01a) ?? ????. 4 18:02:36 2010
######################################################################

CONFIG += qt qwt warn_on debug silent
=======
# Automatically generated by qmake (2.01a) ?? ????. 2 23:49:47 2010
######################################################################

>>>>>>> a287c53e4195f79dc06c35a2760330f2fe23ac8e
TEMPLATE = app
TARGET = 
DEPENDPATH += . src ui src/reuseable src/spectrumwindow
INCLUDEPATH += . src/reuseable src src/spectrumwindow

# Input
HEADERS += src/jyparser.h \
           src/mainwindow.h \
           src/parsersettingsdialog.h \
           src/reuseable/dmenu.h \
           src/reuseable/dmenu_p.h \
           src/reuseable/falgorithms.h \
           src/reuseable/history.h \
           src/reuseable/pointf.h \
           src/reuseable/polygon.h \
           src/reuseable/rangebox.h \
           src/reuseable/selectrecentmenu.h \
           src/reuseable/selectrecentmenu_p.h \
           src/reuseable/settings.h \
           src/reuseable/vectortable.h \
           src/reuseable/windowmenu.h \
           src/reuseable/windowmenu_p.h \
<<<<<<< HEAD
           src/spectrumwindow/curvesettings.h \
           src/spectrumwindow/spectrumsettings.h \
           src/spectrumwindow/spectrumsettingswizard.h \
           src/spectrumwindow/spectrumwindow.h
FORMS += ui/curvesettings.ui \
=======
           src/spectrumwindow/curvesettingsdialog.h \
           src/spectrumwindow/dispensationwindow.h \
           src/spectrumwindow/reportwindow.h \
           src/spectrumwindow/spectrumsettingsdialog.h \
           src/spectrumwindow/spectrumwindow.h
FORMS += ui/curvesettingsdialog.ui \
>>>>>>> a287c53e4195f79dc06c35a2760330f2fe23ac8e
         ui/mainwindow.ui \
         ui/parsersettingsdialog.ui \
         ui/spectrumsettings.ui
SOURCES += src/jyparser.cpp \
           src/main.cpp \
           src/mainwindow.cpp \
           src/parsersettingsdialog.cpp \
           src/reuseable/dmenu.cpp \
           src/reuseable/dmenu_p.cpp \
           src/reuseable/history.cpp \
           src/reuseable/pointf.cpp \
           src/reuseable/polygon.cpp \
           src/reuseable/rangebox.cpp \
           src/reuseable/selectrecentmenu.cpp \
           src/reuseable/selectrecentmenu_p.cpp \
           src/reuseable/settings.cpp \
           src/reuseable/vectortable.cpp \
           src/reuseable/windowmenu.cpp \
           src/reuseable/windowmenu_p.cpp \
<<<<<<< HEAD
           src/spectrumwindow/curvesettings.cpp \
           src/spectrumwindow/spectrumsettings.cpp \
           src/spectrumwindow/spectrumsettingswizard.cpp \
=======
           src/spectrumwindow/curvesettingsdialog.cpp \
           src/spectrumwindow/dispensationwindow.cpp \
           src/spectrumwindow/reportwindow.cpp \
           src/spectrumwindow/spectrumsettingsdialog.cpp \
>>>>>>> a287c53e4195f79dc06c35a2760330f2fe23ac8e
           src/spectrumwindow/spectrumwindow.cpp
